import type { Metadata } from 'next'
import { Nanum_Gothic_Coding } from 'next/font/google'
import './globals.css'

const nanumGothicCoding = Nanum_Gothic_Coding({
  weight: ['400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nanumGothicCoding.className}>
        <header>
          <nav>hajongon</nav>
        </header>
        {children}
      </body>
    </html>
  )
}
